classdef ConeTypingColors
    properties (Constant)
        LOOKUP = containers.Map({edu.washington.riekelab.baudin.protocols.ConeTyping.RED_IDENTIFIER, ...
            edu.washington.riekelab.baudin.protocols.ConeTyping.GREEN_IDENTIFIER, ...
            edu.washington.riekelab.baudin.protocols.ConeTyping.UV_IDENTIFIER}, ...
            {[0.8 0.2 0.2], [0.2 0.8 0.2], [0.2 0.2 0.8]});
    end
end